/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Vitals;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.MyNumericVerifier;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author gorubhambhani
 */
public class CreateVitalSignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalSignJPanel
     */
    
    private Patient patient;
    private JPanel userProcessContainer;
    
    public CreateVitalSignJPanel(JPanel upc, Patient patient) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.patient = patient;
        addVerifiers();
    }
    
    private void addVerifiers(){
        InputVerifier integerVerifier = new MyNumericVerifier();
        tfRespRate.setInputVerifier(integerVerifier);
        tfHeartRate.setInputVerifier(integerVerifier);
        tfBloodPress.setInputVerifier(integerVerifier);
        tfWeight.setInputVerifier(integerVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblRespRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblBloodPress = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        tfRespRate = new javax.swing.JTextField();
        tfHeartRate = new javax.swing.JTextField();
        tfBloodPress = new javax.swing.JTextField();
        tfWeight = new javax.swing.JTextField();
        btnCreateVitals = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Vitals");

        lblRespRate.setText("Respiratory Rate");

        lblHeartRate.setText("Heart Rate");

        lblBloodPress.setText("Blood Pressure");

        lblWeight.setText("Weight");

        tfHeartRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHeartRateActionPerformed(evt);
            }
        });

        tfBloodPress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBloodPressActionPerformed(evt);
            }
        });

        btnCreateVitals.setText("Create");
        btnCreateVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVitalsActionPerformed(evt);
            }
        });

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBloodPress)
                            .addComponent(lblWeight)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRespRate, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblHeartRate)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCreateVitals))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfHeartRate)
                                        .addComponent(tfWeight)
                                        .addComponent(tfBloodPress, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRespRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespRate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeartRate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBloodPress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodPress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeight))
                .addGap(18, 18, 18)
                .addComponent(btnCreateVitals)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(371, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfHeartRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHeartRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHeartRateActionPerformed

    private void tfBloodPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBloodPressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBloodPressActionPerformed

    private void btnCreateVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVitalsActionPerformed
        // TODO add your handling code here:
        
        try {
            int respRate = Integer.parseInt(tfRespRate.getText());
            int heartRate = Integer.parseInt(tfHeartRate.getText());
            int bloodPress = Integer.parseInt(tfBloodPress.getText());
            int weight = Integer.parseInt(tfWeight.getText());
            
            VitalSigns vitalSign = patient.getVitalSignHistory().createAndAddVitalSign();
            vitalSign.setRespiratoryRate(respRate);
            vitalSign.setHeartRate(heartRate);
            vitalSign.setBloodPressure(bloodPress);
            vitalSign.setWeight(weight);
            
            vitalSign.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Vital Sign Added!", "Update", JOptionPane.INFORMATION_MESSAGE);
            
            clearFields();
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Please enter correct values!", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateVitalsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void clearFields() {
        tfRespRate.setText("");
        tfHeartRate.setText("");
        tfBloodPress.setText("");
        tfWeight.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBloodPress;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblRespRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField tfBloodPress;
    private javax.swing.JTextField tfHeartRate;
    private javax.swing.JTextField tfRespRate;
    private javax.swing.JTextField tfWeight;
    // End of variables declaration//GEN-END:variables
}
